---
services:
  gateway:
    image: bwdesigngroup/ignition-docker:8.1.32
    hostname: <project-name>
    volumes:
      - ./ignition-data:/workdir
      - ./backups/gateway.gwbk:/restore.gwbk
    environment:
      SYMLINK_GITIGNORE: false
      SYMLINK_LOGBACK: false
      GATEWAY_SYSTEM_NAME: <project-name>
      GATEWAY_PUBLIC_HTTPS_PORT: 443
      GATEWAY_PUBLIC_ADDRESS: <project-name>.localtest.me
    labels:
      traefik.enable: "true"
      traefik.hostname: "<project-name>"
    command: >
      -r /restore.gwbk
    networks:
      - default
      - proxy

networks:
  default:
  proxy:
    external: true
    name: proxy
