---
repos:
  - repo: local
    hooks:
      - id: shellcheck
        name: Shellcheck
        entry: shellcheck
        language: system
        types: [shell]
        files: \.sh$
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          - --rcfile=linting/.pylintrc
          - "--msg-template=\"{path}({line}): [{obj}] {msg} ({symbol})\""
      - id: markdownlint
        name: markdownlint
        entry: markdownlint
        language: system
        types: [markdown]
        args:
          - --config=linting/.markdownlint.json
          - --ignore-path=linting/.markdownlintignore
      - id: yamllint
        name: yamllint
        entry: yamllint
        language: system
        types: [yaml]
        files: \.yaml$
        args:
          - --config-file=linting/.yamllint
