---
name: Lint Code

on:
    pull_request:
        paths:
            - '**/*.py'
            - '**/*.md'
            - '**/*.sh'
            - '**/*.yaml'
            - '**/*.yml'
        branches: [master, development]
    push:
        paths:
            - '**/*.py'
            - '**/*.md'
            - '**/*.sh'
            - '**/*.yaml'
            - '**/*.yml'
        branches: [master, development]

    workflow_dispatch: 


jobs:
    pylint:
        name: Lint Python Code
        runs-on: ubuntu-20.04
        container: python:2.7.18-buster

        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install pylint
            - name: Run pylint and ensure a perfect score
              run: |
                find . -name "*.py" | \
                xargs pylint \
                    --msg-template="{path}({line}): [{obj}] {msg} ({symbol})" \
                    --rcfile=linting/.pylintrc

    markdownlint:
        name: Lint Markdown
        runs-on: ubuntu-20.04

        steps:
            - uses: actions/checkout@v2
            - name: Set up Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: '19.x'
            - name: Install dependencies
              run: |
                npm install -g markdownlint-cli
            - name: Run markdownlint
              run: |
                find . -name "*.md" | \
                xargs markdownlint --config linting/.markdownlint.json

    shellcheck:
        name: Lint Shell Files
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Run ShellCheck
              uses: ludeeus/action-shellcheck@master

    yamllint:
        name: Lint YAML Files
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Run yamllint
              uses: karancode/yamllint-github-action@master
              with:
                yamllint_config_filepath: linting/.yamllint
