---
name: Automated Tests

on: [pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-20.04
    container: python:2.7.18-buster

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Check Files
        run: |
            find ./tests -type f -name "*.py" | \
            python -m pytest -s -rfsE -p no:cacheprovider
